### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Viper-Bit**
creating two same page with different themes is tricky, because we cant use duplicate global keys and 2 pages will not share states so for example drawer will close on creating new page.

**Solution :**
save screenshot of old Theme page and create new page with new theme, so we just recreate old page with new theme and same state.

### CODE REVIEW

**Comment by kherel** [comment]
Super. Great job.

**Comment by kherel** [comment]
We are not using the same global keys, different trees has own keys, created Theme Switcher widget.

But I've agree that creating screenshots could be more save solution. Plus I didn't check my version with a drawer. 

I've noticed some exceptions in your example, it's happens when you change the speed.
```
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

```

Thanks for cleaning.

**Comment by kherel** [comment]
It was because of timeDilation.
I'll remove it from the example.

**Comment by kherel** [comment]
I've fix it, by adding one more global key )))

**Comment by Viper-Bit** [comment]
@kherel thx for fix.

**Pull request merged**
